dist: trusty
language: php

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3

matrix:

before_script:
  - travis_retry composer update --prefer-stable --prefer-lowest --no-interaction --prefer-dist

addons:
  sonarcloud:
    organization: "dcsg-github"

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --coverage-clover=/tmp/coverage.xml --log-junit=/tmp/test-results.xml

after_script:
  - sonar-scanner
