language: php

dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3

matrix:

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

before_script:
  - composer install

addons:
  sonarcloud:
    organization: "dcsg-github"

script:
  - vendor/bin/phpunit --coverage-clover=/tmp/coverage.xml --log-junit=/tmp/test-results.xml
  - sonar-scanner
